"""Render already-detected clusters as a single static HTML page.

Pure string templating — no JavaScript, no external assets, no network. It only
formats the cluster rows the detector has already written; it does not fetch,
track, or watch anything. Useful for a quick read-only summary you can open in a
browser or attach to a report.
"""

from __future__ import annotations

import html
from typing import Any

_STYLE = """
* { box-sizing: border-box; }
body { font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif;
       margin: 0; padding: 2rem; background: #0f172a; color: #e2e8f0; }
h1 { font-size: 1.4rem; margin: 0 0 .25rem; }
.sub { color: #94a3b8; margin: 0 0 1.5rem; font-size: .85rem; }
table { width: 100%; border-collapse: collapse; font-size: .85rem; }
th, td { text-align: left; padding: .45rem .6rem; border-bottom: 1px solid #334155; }
th { color: #cbd5e1; }
.tier { padding: .1rem .5rem; border-radius: 999px; font-size: .75rem; font-weight: 600; }
.mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
.note { color: #94a3b8; font-size: .78rem; margin-top: 1.5rem; }
"""

_TIER_COLOR = {
    "S": "#34d399",
    "A": "#60a5fa",
    "B": "#fbbf24",
    "C": "#94a3b8",
}


def _tier_badge(tier: str) -> str:
    color = _TIER_COLOR.get(tier.upper(), "#475569")
    return f'<span class="tier" style="background:{color};color:#0f172a">{html.escape(tier)}</span>'


def render_clusters_html(rows: list[dict[str, Any]], *, title: str = "Detected clusters") -> str:
    """Render detected-cluster rows as a standalone HTML document.

    ``rows`` are the dicts produced by the ``export`` path:
    ``token, wallet_count, score, tier, timestamp, total_usd``.
    """
    body_rows = []
    for row in rows:
        total_usd = float(row.get("total_usd") or 0.0)
        body_rows.append(
            "<tr>"
            f'<td class="mono">{html.escape(str(row.get("token", "")))}</td>'
            f"<td>{_tier_badge(str(row.get('tier', '?')))}</td>"
            f"<td>{int(row.get('score', 0))}</td>"
            f"<td>{int(row.get('wallet_count', 0))}</td>"
            f"<td>${total_usd:,.0f}</td>"
            f"<td>{html.escape(str(row.get('timestamp', '')))}</td>"
            "</tr>"
        )
    rows_html = "\n".join(body_rows) or '<tr><td colspan="6">No clusters.</td></tr>'
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>{_STYLE}</style></head>
<body>
<h1>{html.escape(title)}</h1>
<p class="sub">Read-only summary of clusters already detected from public on-chain data.</p>
<table>
<thead><tr><th>Token</th><th>Tier</th><th>Score</th><th>Wallets</th><th>Total USD</th><th>Detected</th></tr></thead>
<tbody>
{rows_html}
</tbody>
</table>
<p class="note">Generated by wallet-cluster-detector. Framework/research output on public data;
not financial advice and not individual surveillance.</p>
</body></html>
"""
